name: called

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  called-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: env
      - run: "echo secret 1: ${{ secrets.secret1 }}"
      - run: "echo secret 2: ${{ secrets.secret2 }}"
      - run: "echo secret 3: ${{ secrets.secret3 }}"
      - run: "echo var 1: ${{ vars.var1 }}"
      - run: "echo var 2: ${{ vars.var2 }}"
    
