name: NEW MANUAL WORKFLOW

on:
  workflow_dispatch:
    inputs:
      container-tag:
        required: true
        type: string
        description: Docker container tag

jobs:
  do-the-thing:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'this is a message'
