name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo 'deploying to dev'

  deploy-qa:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - run: |
          curl -sN "${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals"

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Retrieve testing evidence
        id: retrieve-testing-evidence
        run: |
          prod_approval_comment_jq_filter='map(select(.environments[0].name == "prod")) | .[0].comment'
          approvals_api_url="${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals"
          approval_comment="$(curl -sN $approvals_api_url | jq -Mr $prod_approval_comment_jq_filter)"
          if [ $approval_comment = 'null' ]; then
            echo 'Could not retrieve testing evidence. Aborting deployment.'
          fi

          echo "testing_evidence=$approval_comment" >> $GITHUB_OUTPUT
      - name: Print testing evidence
        run: |
          echo "${{ steps.retrieve_testing_evidence.outputs.testing_evidence }}"
