name: Test

on:
  push:

jobs:
  job1:
    name: Test 1
    runs-on: ubuntu-latest
    outputs:
      bark: ${{ steps.step1.outputs.test }}
      two: ruff
    steps:
      - id: step1
        run: |
          echo "hello 1"
          echo "bark=woof" >> "$GITHUB_OUTPUT"

  job2:
    name: Test 2
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ github.run_attempt > 1 }}
    environment: qa
    steps:
      - run: |
          echo "hello 2: ${{ needs.job1.outputs.two }}"

  job3:
    name: Test 3
    runs-on: ubuntu-latest
    needs: [job1, job2]
    environment: prod
    steps:
      - run: |
          echo "hello 3: ${{ needs.job1.outputs.two }}"
