name: Test

on:
  push:

jobs:
  job1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello 1"

  job2:
    name: Test 2
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ github.run_attempt > 1 }}
    environment: qa
    steps:
      - run: |
          echo "hello 2"

  job3:
    name: Test 3
    runs-on: ubuntu-latest
    needs: job2
    environment: prod
    steps:
      - run: |
          echo "hello 3"
